// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShippingCalc.Data;

#nullable disable

namespace ShippingCalc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241021174647_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ShippingCalc.Models.ObjectItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoralBitsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoubleKrabbyPattyCount")
                        .HasColumnType("INTEGER");

                    b.Property<float>("GrantTotal")
                        .HasColumnType("REAL");

                    b.Property<int>("KelpFriesCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KelpShakeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KrabbyMealCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KrabbyPattyCount")
                        .HasColumnType("INTEGER");

                    b.Property<float>("TaxAll")
                        .HasColumnType("REAL");

                    b.Property<float>("TipAll")
                        .HasColumnType("REAL");

                    b.Property<float>("TotalAll")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Objects");
                });
#pragma warning restore 612, 618
        }
    }
}
